### This file is automatically generated by Qt Design Studio.
### Do not change

add_subdirectory(OFPData)
add_subdirectory(OFPContent)
add_subdirectory(App)

target_link_libraries(${CMAKE_PROJECT_NAME} PRIVATE
        OFPDataplugin
	OFPContentplugin)
